---
title: "Haunted Locations"
output: html_document
date: "2023-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data and Packages

```{r packages}
library(tidyverse)       # Tidyverse for Tidy Data
library(readxl)
library(tmap)            # Thematic Mapping
library(tmaptools) 
library(tigris)          # Get Census Geography Poloygons
library(sf)

haunted_places <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-10-10/haunted_places.csv')

```
```{r geo_data}

# load geographical data for usa
us_geo <- tigris::states(class = "sf") 
```

```{r site_map}
# calculate haunted sites per state
haunted_sites_per_state <- haunted_places |>
  group_by(state_abbrev) |>
  summarize(num_haunted_sites = n()) |>
  rename(STUSPS = "state_abbrev")

# join the haunted sites with map data
HelperShapeObject <- left_join(us_geo, haunted_sites_per_state, by = c("STUSPS" = "STUSPS"))

# shift far away states closer
contiguous_states <- HelperShapeObject %>% 
  filter(REGION != 9) %>% 
  shift_geometry()

#reshaping box so the legend doesn't overlap
bbox_new <- st_bbox(contiguous_states)

xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
yrange <- bbox_new$ymax - bbox_new$ymin # range of y values

# bbox_new[1] <- bbox_new[1] - (0.25 * xrange) # xmin - left
 bbox_new[3] <- bbox_new[3] + (.5 * xrange) # xmax - right
# bbox_new[2] <- bbox_new[2] - (0.25 * yrange) # ymin - bottom
bbox_new[4] <- bbox_new[4] + (0.2 * yrange) # ymax - top

bbox_new <- bbox_new |>  # take the bounding box ...
  st_as_sfc() # ... and make it a sf polygon

# draw the map
tm_shape(contiguous_states, bbox = bbox_new) +
  tm_polygons("num_haunted_sites", id = "Name", title = 'Number of Haunted Sites') +
  tm_layout(title = 'Concentration of Haunted Sites across the United States')
```

